package sap_api_input_reader

type EC_MC struct {
	ConnectionKey string `json:"connection_key"`
	Result        bool   `json:"result"`
	RedisKey      string `json:"redis_key"`
	Filepath      string `json:"filepath"`
	Document      struct {
		DocumentNo     string `json:"document_no"`
		DeliverTo      string `json:"deliver_to"`
		Quantity       string `json:"quantity"`
		PickedQuantity string `json:"picked_quantity"`
		Price          string `json:"price"`
		Batch          string `json:"batch"`
	} `json:"document"`
	ProductionOrder struct {
		DocumentNo           string `json:"document_no"`
		Status               string `json:"status"`
		DeliverTo            string `json:"deliver_to"`
		Quantity             string `json:"quantity"`
		CompletedQuantity    string `json:"completed_quantity"`
		PlannedStartDate     string `json:"planned_start_date"`
		PlannedValidatedDate string `json:"planned_validated_date"`
		ActualStartDate      string `json:"actual_start_date"`
		ActualValidatedDate  string `json:"actual_validated_date"`
		Batch                string `json:"batch"`
		Work                 struct {
			WorkNo                   string `json:"work_no"`
			Quantity                 string `json:"quantity"`
			CompletedQuantity        string `json:"completed_quantity"`
			ErroredQuantity          string `json:"errored_quantity"`
			Component                string `json:"component"`
			PlannedComponentQuantity string `json:"planned_component_quantity"`
			PlannedStartDate         string `json:"planned_start_date"`
			PlannedStartTime         string `json:"planned_start_time"`
			PlannedValidatedDate     string `json:"planned_validated_date"`
			PlannedValidatedTime     string `json:"planned_validated_time"`
			ActualStartDate          string `json:"actual_start_date"`
			ActualStartTime          string `json:"actual_start_time"`
			ActualValidatedDate      string `json:"actual_validated_date"`
			ActualValidatedTime      string `json:"actual_validated_time"`
		} `json:"work"`
	} `json:"production_order"`
	APISchema      string `json:"api_schema"`
	MaterialCode   string `json:"material_code"`
	Plant_Supplier string `json:"plant/supplier"`
	Stock          string `json:"stock"`
	DocumentType   string `json:"document_type"`
	DocumentNo     string `json:"document_no"`
	PlannedDate    string `json:"planned_date"`
	ValidatedDate  string `json:"validated_date"`
	Deleted        bool   `json:"deleted"`
}

type SDC struct {
	ConnectionKey           string `json:"connection_key"`
	Result                  bool   `json:"result"`
	RedisKey                string `json:"redis_key"`
	Filepath                string `json:"filepath"`
	CustomerOrderCollection struct {
		ObjectID                                                 string `json:"ObjectID"`
		InformationLifeCycleStatusCode                           string `json:"InformationLifeCycleStatusCode"`
		InformationLifeCycleStatusCodeText                       string `json:"InformationLifeCycleStatusCodeText"`
		ClassificationCode                                       string `json:"ClassificationCode"`
		ClassificationCodeText                                   string `json:"ClassificationCodeText"`
		BuyerID                                                  string `json:"BuyerID"`
		FulfilmentBlockingReasonCode                             string `json:"FulfilmentBlockingReasonCode"`
		FulfilmentBlockingReasonCodeText                         string `json:"FulfilmentBlockingReasonCodeText"`
		ID                                                       string `json:"ID"`
		InvoicingBlockingReasonCode                              string `json:"InvoicingBlockingReasonCode"`
		InvoicingBlockingReasonCodeText                          string `json:"InvoicingBlockingReasonCodeText"`
		LastChangeDate                                           string `json:"LastChangeDate"`
		OrderExternalLifeCycleStatusCode                         string `json:"OrderExternalLifeCycleStatusCode"`
		OrderExternalLifeCycleStatusCodeText                     string `json:"OrderExternalLifeCycleStatusCodeText"`
		Name                                                     string `json:"Name"`
		LanguageCode                                             string `json:"LanguageCode"`
		LanguageCodeText                                         string `json:"LanguageCodeText"`
		ProcessingTypeCode                                       string `json:"ProcessingTypeCode"`
		ProcessingTypeCodeText                                   string `json:"ProcessingTypeCodeText"`
		ItemListCancellationStatusCode                           string `json:"ItemListCancellationStatusCode"`
		ItemListCancellationStatusCodeText                       string `json:"ItemListCancellationStatusCodeText"`
		ItemListFulfilmentProcessingStatusCode                   string `json:"ItemListFulfilmentProcessingStatusCode"`
		ItemListFulfilmentProcessingStatusCodeText               string `json:"ItemListFulfilmentProcessingStatusCodeText"`
		ApprovalStatusCode                                       string `json:"ApprovalStatusCode"`
		ApprovalStatusCodeText                                   string `json:"ApprovalStatusCodeText"`
		ConsistencyStatusCode                                    string `json:"ConsistencyStatusCode"`
		ConsistencyStatusCodeText                                string `json:"ConsistencyStatusCodeText"`
		OverallBlockingStatusCode                                string `json:"OverallBlockingStatusCode"`
		OverallBlockingStatusCodeText                            string `json:"OverallBlockingStatusCodeText"`
		ReplicationProcessingStatusCode                          string `json:"ReplicationProcessingStatusCode"`
		ReplicationProcessingStatusCodeText                      string `json:"ReplicationProcessingStatusCodeText"`
		DistributionChannelCode                                  string `json:"DistributionChannelCode"`
		DistributionChannelCodeText                              string `json:"DistributionChannelCodeText"`
		DivisionCode                                             string `json:"DivisionCode"`
		DivisionCodeText                                         string `json:"DivisionCodeText"`
		SalesGroupID                                             string `json:"SalesGroupID"`
		SalesOfficeID                                            string `json:"SalesOfficeID"`
		SalesOrganisationID                                      string `json:"SalesOrganisationID"`
		SalesTerritoryID                                         string `json:"SalesTerritoryID"`
		BuyerPartyID                                             string `json:"BuyerPartyID"`
		DeliveryPriorityCode                                     string `json:"DeliveryPriorityCode"`
		DeliveryPriorityCodeText                                 string `json:"DeliveryPriorityCodeText"`
		TransferLocationName                                     string `json:"TransferLocationName"`
		EmployeeResponsiblePartyID                               string `json:"EmployeeResponsiblePartyID"`
		BuyerPartyName                                           string `json:"BuyerPartyName"`
		EmployeeResponsiblePartyName                             string `json:"EmployeeResponsiblePartyName"`
		BuyerContactPartyID                                      string `json:"BuyerContactPartyID"`
		BuyerContactPartyName                                    string `json:"BuyerContactPartyName"`
		CurrencyCode                                             string `json:"CurrencyCode"`
		CurrencyCodeText                                         string `json:"CurrencyCodeText"`
		PriceDateTime                                            string `json:"PriceDateTime"`
		ProductRecipientPartyID                                  string `json:"ProductRecipientPartyID"`
		ProductRecipientPartyName                                string `json:"ProductRecipientPartyName"`
		RequestedFulfillmentStartDateTime                        string `json:"RequestedFulfillmentStartDateTime"`
		TimeZoneCode                                             string `json:"TimeZoneCode"`
		TimeZoneCodeText                                         string `json:"TimeZoneCodeText"`
		CancellationReasonCode                                   string `json:"CancellationReasonCode"`
		CancellationReasonCodeText                               string `json:"CancellationReasonCodeText"`
		SalesUnitPartyID                                         string `json:"SalesUnitPartyID"`
		CalculationStatusCode                                    string `json:"CalculationStatusCode"`
		CalculationStatusCodeText                                string `json:"CalculationStatusCodeText"`
		ExternalPriceDocumentBaseBusinessTransactionDocumentUUID string `json:"ExternalPriceDocumentBaseBusinessTransactionDocumentUUID"`
		PricingProcedureCode                                     string `json:"PricingProcedureCode"`
		PricingProcedureCodeText                                 string `json:"PricingProcedureCodeText"`
		DateTime                                                 string `json:"DateTime"`
		OrderReasonCode                                          string `json:"OrderReasonCode"`
		OrderReasonCodeText                                      string `json:"OrderReasonCodeText"`
		MaintenanceModeInternalOnlyMainDiscount                  string `json:"MaintenanceModeInternalOnlyMainDiscount"`
		NetAmount                                                string `json:"NetAmount"`
		NetAmountCurrencyCode                                    string `json:"NetAmountCurrencyCode"`
		NetAmountCurrencyCodeText                                string `json:"NetAmountCurrencyCodeText"`
		GrossAmount                                              string `json:"GrossAmount"`
		GrossAmountCurrencyCode                                  string `json:"GrossAmountCurrencyCode"`
		GrossAmountCurrencyCodeText                              string `json:"GrossAmountCurrencyCodeText"`
		TaxAmount                                                string `json:"TaxAmount"`
		TaxAmountCurrencyCode                                    string `json:"TaxAmountCurrencyCode"`
		TaxAmountCurrencyCodeText                                string `json:"TaxAmountCurrencyCodeText"`
		InternalPricingProcedureCode                             string `json:"InternalPricingProcedureCode"`
		InternalPricingProcedureCodeText                         string `json:"InternalPricingProcedureCodeText"`
		InternalPricingCalculationStatusCode                     string `json:"InternalPricingCalculationStatusCode"`
		InternalPricingCalculationStatusCodeText                 string `json:"InternalPricingCalculationStatusCodeText"`
		NetWeightMeasure                                         string `json:"NetWeightMeasure"`
		NetWeightUnitCode                                        string `json:"NetWeightUnitCode"`
		NetWeightUnitCodeText                                    string `json:"NetWeightUnitCodeText"`
		GrossWeightMeasure                                       string `json:"GrossWeightMeasure"`
		GrossWeightUnitCode                                      string `json:"GrossWeightUnitCode"`
		GrossWeightUnitCodeText                                  string `json:"GrossWeightUnitCodeText"`
		VolumeMeasure                                            string `json:"VolumeMeasure"`
		VolumeUnitCode                                           string `json:"VolumeUnitCode"`
		VolumeUnitCodeText                                       string `json:"VolumeUnitCodeText"`
		Simulate                                                 string `json:"Simulate"`
		SubmitForApproval                                        string `json:"SubmitForApproval"`
		Transfer                                                 string `json:"Transfer"`
		WithdrawFromApproval                                     string `json:"WithdrawFromApproval"`
		SetAsCompleted                                           string `json:"SetAsCompleted"`
		PlantPartyID                                             string `json:"PlantPartyID"`
		PlantPartyName                                           string `json:"PlantPartyName"`
		CreatedBy                                                string `json:"CreatedBy"`
		LastChangedBy                                            string `json:"LastChangedBy"`
		CreationIdentityUUID                                     string `json:"CreationIdentityUUID"`
		LastChangeIdentityUUID                                   string `json:"LastChangeIdentityUUID"`
		EntityLastChangedOn                                      string `json:"EntityLastChangedOn"`
		ETag                                                     string `json:"ETag"`
		DataloaderKUT                                            string `json:"DataloaderKUT"`
		CustomerOrderAttachmentFolder                            string `json:"CustomerOrderAttachmentFolder"`
		CustomerOrderCashDiscountTerms                           struct {
			ObjectID           string `json:"ObjectID"`
			ParentObjectID     string `json:"ParentObjectID"`
			Code               string `json:"Code"`
			CodeText           string `json:"CodeText"`
			SalesOrderID       string `json:"SalesOrderID"`
			ETag               string `json:"ETag"`
			CustomerOrderItems struct {
				ObjectID                                      string `json:"ObjectID"`
				ParentObjectID                                string `json:"ParentObjectID"`
				Description                                   string `json:"Description"`
				LanguageCode                                  string `json:"LanguageCode"`
				LanguageCodeText                              string `json:"LanguageCodeText"`
				CreationDate                                  string `json:"CreationDate"`
				ParentItemID                                  string `json:"ParentItemID"`
				ID                                            string `json:"ID"`
				ProcessingTypeCode                            string `json:"ProcessingTypeCode"`
				ProcessingTypeCodeText                        string `json:"ProcessingTypeCodeText"`
				ProductID                                     string `json:"ProductID"`
				ProductStandardID                             string `json:"ProductStandardID"`
				ProductInternalID                             string `json:"ProductInternalID"`
				Quantity                                      string `json:"Quantity"`
				QuantityMeasureUnitCode                       string `json:"QuantityMeasureUnitCode"`
				QuantityMeasureUnitCodeText                   string `json:"QuantityMeasureUnitCodeText"`
				StartDateTime                                 string `json:"StartDateTime"`
				TimeZoneCode                                  string `json:"TimeZoneCode"`
				TimeZoneCodeText                              string `json:"TimeZoneCodeText"`
				SalesTermsCancellationReasonCode              string `json:"SalesTermsCancellationReasonCode"`
				SalesTermsCancellationReasonCodeText          string `json:"SalesTermsCancellationReasonCodeText"`
				MaintenanceModeInternalOnlyItemMainDiscount   string `json:"MaintenanceModeInternalOnlyItemMainDiscount"`
				ItemProductRecipientBusinessPartnerInternalID string `json:"ItemProductRecipientBusinessPartnerInternalID"`
				BuyerID                                       string `json:"BuyerID"`
				ProductBuyerID                                string `json:"ProductBuyerID"`
				SalesOrderID                                  string `json:"SalesOrderID"`
				NetAmount                                     string `json:"NetAmount"`
				NetAmountCurrencyCode                         string `json:"NetAmountCurrencyCode"`
				NetAmountCurrencyCodeText                     string `json:"NetAmountCurrencyCodeText"`
				NetPriceAmount                                string `json:"NetPriceAmount"`
				NetPriceAmountCurrencyCode                    string `json:"NetPriceAmountCurrencyCode"`
				NetPriceAmountCurrencyCodeText                string `json:"NetPriceAmountCurrencyCodeText"`
				TaxAmount                                     string `json:"TaxAmount"`
				TaxAmountCurrencyCode                         string `json:"TaxAmountCurrencyCode"`
				TaxAmountCurrencyCodeText                     string `json:"TaxAmountCurrencyCodeText"`
				NetWeightMeasure                              string `json:"NetWeightMeasure"`
				NetWeightUnitCode                             string `json:"NetWeightUnitCode"`
				NetWeightUnitCodeText                         string `json:"NetWeightUnitCodeText"`
				GrossWeightMeasure                            string `json:"GrossWeightMeasure"`
				GrossWeightUnitCode                           string `json:"GrossWeightUnitCode"`
				GrossWeightUnitCodeText                       string `json:"GrossWeightUnitCodeText"`
				VolumeMeasure                                 string `json:"VolumeMeasure"`
				VolumeUnitCode                                string `json:"VolumeUnitCode"`
				VolumeUnitCodeText                            string `json:"VolumeUnitCodeText"`
				NetPriceBaseQuantity                          string `json:"NetPriceBaseQuantity"`
				NetPriceBaseQuantityunitCode                  string `json:"NetPriceBaseQuantityunitCode"`
				NetPriceBaseQuantityunitCodeText              string `json:"NetPriceBaseQuantityunitCodeText"`
				PlantPartyID                                  string `json:"PlantPartyID"`
				PlantName                                     string `json:"PlantName"`
				LifeCycleStatusCode                           string `json:"LifeCycleStatusCode"`
				LifeCycleStatusCodeText                       string `json:"LifeCycleStatusCodeText"`
				CancellationStatusCode                        string `json:"CancellationStatusCode"`
				CancellationStatusCodeText                    string `json:"CancellationStatusCodeText"`
				FulfilmentProcessingStatusCode                string `json:"FulfilmentProcessingStatusCode"`
				FulfilmentProcessingStatusCodeText            string `json:"FulfilmentProcessingStatusCodeText"`
				InvoiceProcessingStatusCode                   string `json:"InvoiceProcessingStatusCode"`
				InvoiceProcessingStatusCodeText               string `json:"InvoiceProcessingStatusCodeText"`
				EntityLastChangedOn                           string `json:"EntityLastChangedOn"`
				ETag                                          string `json:"ETag"`
				CustomerOrderParty                            struct {
					ObjectID                                 string `json:"ObjectID"`
					ParentObjectID                           string `json:"ParentObjectID"`
					TimeZoneCode                             string `json:"TimeZoneCode"`
					TimeZoneCodeText                         string `json:"TimeZoneCodeText"`
					PartyName                                string `json:"PartyName"`
					PartyID                                  string `json:"PartyID"`
					RoleCode                                 string `json:"RoleCode"`
					RoleCodeText                             string `json:"RoleCodeText"`
					SalesOrderID                             string `json:"SalesOrderID"`
					PreferredCommunicationMediumTypeCode     string `json:"PreferredCommunicationMediumTypeCode"`
					PreferredCommunicationMediumTypeCodeText string `json:"PreferredCommunicationMediumTypeCodeText"`
					MainIndicator                            string `json:"MainIndicator"`
					ConventionalPhone                        string `json:"ConventionalPhone"`
					Email                                    string `json:"Email"`
					Web                                      string `json:"Web"`
					Fax                                      string `json:"Fax"`
					MobilePhone                              string `json:"MobilePhone"`
					FirstLineName                            string `json:"FirstLineName"`
					SecondLineName                           string `json:"SecondLineName"`
					ThirdLineName                            string `json:"ThirdLineName"`
					FourthLineName                           string `json:"FourthLineName"`
					CareOfName                               string `json:"CareOfName"`
					CityName                                 string `json:"CityName"`
					CountryCode                              string `json:"CountryCode"`
					CountryCodeText                          string `json:"CountryCodeText"`
					CountyName                               string `json:"CountyName"`
					DistrictName                             string `json:"DistrictName"`
					StreetPrefixName                         string `json:"StreetPrefixName"`
					AdditionalStreetPrefixName               string `json:"AdditionalStreetPrefixName"`
					HouseID                                  string `json:"HouseID"`
					StreetName                               string `json:"StreetName"`
					StreetSuffixName                         string `json:"StreetSuffixName"`
					AdditionalStreetSuffixName               string `json:"AdditionalStreetSuffixName"`
					RegionCode                               string `json:"RegionCode"`
					RegionCodeText                           string `json:"RegionCodeText"`
					StreetPostalCode                         string `json:"StreetPostalCode"`
					POBoxIndicator                           string `json:"POBoxIndicator"`
					POBoxID                                  string `json:"POBoxID"`
					POBoxPostalCode                          string `json:"POBoxPostalCode"`
					POBoxDeviatingCityName                   string `json:"POBoxDeviatingCityName"`
					POBoxDeviatingCountryCode                string `json:"POBoxDeviatingCountryCode"`
					POBoxDeviatingCountryCodeText            string `json:"POBoxDeviatingCountryCodeText"`
					POBoxDeviatingRegionCode                 string `json:"POBoxDeviatingRegionCode"`
					POBoxDeviatingRegionCodeText             string `json:"POBoxDeviatingRegionCodeText"`
					ETag                                     string `json:"ETag"`
				} `json:"CustomerOrderParty "`
			} `json:"CustomerOrderItems"`
		} `json:"CustomerOrderCashDiscountTerms"`
	} `json:"CustomerOrderCollection"`
	APISchema                   string   `json:"api_schema"`
	Accepter                    []string `json:"accepter"`
	CustomerorderCollectionCode string   `json:"customerorder_Collection_code"`
	Deleted                     bool     `json:"deleted"`
}
